#!/usr/bin/python
import os.path
import serial
import sys

if __name__ == '__main__':
	
	if len(sys.argv) == 3:
		addr = sys.argv[1]
		cmd = sys.argv[2]

	ser = serial.Serial()
	f = open("cfg", "r")
	commport = f.read()
	f.close
	#print("using " + commport)
	ser = serial.Serial(commport, 9600, timeout=2.0)
	ser.write('++addr ' + addr + '\n')
	ser.write(cmd + '\r\n')
	#print("Sending " + cmd)
	if "?" in cmd:
		input = ser.read(256)
		print input,
	ser.close()
